### ISSUE TITLE
Improper Grouping of Integer Params

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#1247]
## 🐛 Bug

Grouping an integer parameter in any way (stroke or color) does not group the runs properly. 

### To reproduce

Not sure. It might be due to the integer type.

### Expected behavior

I have 4 values, [2,4,6,8]. They should be assigned to four groups. Instead, they are assigned to two groups: [2,6] and [4,8].

### Environment

- Aim Version (e.g., 3.0.1): 3.4.0
- Python version: 3.6.10
- pip version: 21.3.1
- OS (e.g., Linux): Linux
- Any other relevant information: N/A

### Additional context

![image](https://user-images.githubusercontent.com/22674819/150668976-3f069d15-f40c-4ce0-87c7-51c11636717e.png)
![image](https://user-images.githubusercontent.com/22674819/150668971-a70558d6-0ab5-4302-babe-c904f82e2119.png)
![image](https://user-images.githubusercontent.com/22674819/150669127-1ae78f7b-1402-4f98-80d5-8201a93b27de.png)

**Comment by roubkar** [comment]
Hey @MohdElgaar, thanks for opening this issue.

This can be caused by `persistence mode`:
<img width="389" alt="Screen Shot 2022-01-23 at 11 53 27" src="https://user-images.githubusercontent.com/9951653/150669559-abfc1042-059a-4cfa-9c12-f6af1cfc15e2.png">

you can press the `Shuffle` button until you'll get the preferred set of colors (where each group will have a unique color)
or toggle the `persistence mode` (disable) so that each group will be colored by its index's corresponding color from the selected palette.

Hope this will help to resolve your issue.

**Comment by MohdElgaar** [comment]
Hey @roubkar. This fixed it. Thanks!
