### ISSUE TITLE
Add ability to explore metrics from the runs list by selecting multiple runs and metrics

### ISSUE THREAD

**Issue by rubenaprikyan** [aimhubio/aim#1313]
## 🚀 Feature

Add ability to explore metrics from the runs list by selecting multiple runs and metrics

### Motivation

It would be a great  experience to be possible to explore metrics from the runs  list, by selecting one or more runs and metrics.

### Pitch
The suggestion is to have `explore` button on runs table, and by clicking on the button after selecting one or more runs,  show the modal or popover to select metrics, then redirect to the metrics explorer with the generated query.

**Comment by ashutoshsaboo** [comment]
Big +1 on this, even within a single run when multiple metrics are logged it'd be useful to have a quick 1-click way to batch select metrics and get redirected to the metrics explorer with those metrics superimposed in a single graph. 

For example: say if i'm logging loss, accuracy over epochs for both train, val, pred set. Selecting both metrics from the run single page and having a way to go to metrics explorer with both these metrics pre-selected would be very beneficial to have. Otherwise user has to go to metrics explorer manually -> click for specific metrics -> search for specific runs -> then plot them. This is like 4 steps of additional work in comparison, if it can be done with a single 1-click automated way itself that'd be quite useful. @rubenaprikyan @SGevorg @gorarakelyan

**Comment by dngfra** [comment]
It would be useful to have this feature not only for metrics but also for images and scatters and link them such that I can visualize the results in all the panels (images, metrics, scatters)  for the same runs by selecting them once in the beginning. I might want to quickly inspect and compare some runs and then quickly switch between metrics and images to check different things but it is unpractical if every time I switch panel I need to reselect which runs to visualize.
