### ISSUE TITLE
Not possible to install on MacBook Pro (M1)

### ISSUE THREAD

**Issue by dariokonopatzki** [aimhubio/aim#1347]
## 🐛 Bug
See title. `pip install aim` results in a series of installation attempts by pip in decreasing order of versions (3.5.4, 3.5.3, ...).

### To reproduce
`pip install aim`, in the environment outlined below.

### Expected behavior
aim installs without error.

### Environment

- Aim Version: None, because installation does not succeed.
- Python version: Tried both 3.9.10 and 3.8.12
- pip version: 21.3.1 respectively 22.0.3
- OS macOS Monterey Version: 12.2.1
- Any other relevant information: I tried to directly install the latest version of aim via `pip install aim==3.5.4`, which results in `ERROR: Could not find a version that satisfies the requirement aimrocks==0.0.10 (from aim) (from versions: none)
ERROR: No matching distribution found for aimrocks==0.0.10`

**Comment by alberttorosyan** [comment]
relates to aimhubio/aimrocks/issues/11

**Comment by alberttorosyan** [comment]
Hey @dimreduct!
Thanks for reporting the issue. The problem cones from the fact that unfortunately we do not have support for M1 in one of the dependencies (you can check the related issue [here](https://github.com/aimhubio/aim/issues/1347#issuecomment-1040739565)).
While we are working on this, I would like to check is this a blocker for you? If this blocks adopting `aim` we can explore possible workarounds.

**Comment by dimreduct** [comment]
Hi @alberttorosyan, thanks for pointing out the existing issue, I had missed it during search.
Unfortunately yes, this is a huge blocker for me. My team is working on an ongoing project which uses aim for our experiment tracking, and since only M1 machines are available now we will need to change that for the time being.
I would be interested in any ideas you have for possible workarounds; for now we can sidestep the issue by tracking experiments with plain text files, but it would be great to be able to switch back to aim as soon as possible instead of having to look for another tracking platform, since I really like this project.

**Comment by alberttorosyan** [comment]
@dimreduct sorry to hear this blocks your team... I noticed that you have tried both Python 3.9 and 3.8. We do have pre-build Python 3.9 binary wheel for `aimrocks`.

So basically the workaround would be the following:
1. `tar xzf aimrocks_0.10.0_macos_arm64.tar.gz`
2. `pip install ./dist/aimrocks-0.0.10-cp39-cp39-macosx_12_0_arm64.whl`
3. `pip install aim`

You can download the tar aimrocks tar file here: [aimrocks_0.10.0_macos_arm64.tar.gz](https://github.com/aimhubio/aim/files/8077138/aimrocks_0.10.0_macos_arm64.tar.gz)

Let me know if this will work for time being.

**Comment by dimreduct** [comment]
Thanks a lot @alberttorosyan, this works!

**Comment by mahnerak** [comment]
Now we have dev branches for `M1` builds for `aim`. To try them out:
```
pip install aim==3.9.0.dev23
```

We'll have M1-compatible stable releases soon!

**Comment by gorarakelyan** [comment]
@dariokonopatzki Aim comes with M1 Macs support since 3.10 version. Please feel free to reopen this issue if you have any trouble with installation.
