### ISSUE TITLE
Set default ordering of Images and Audios tabs steps to desc

### ISSUE THREAD

**Issue by VkoHov** [aimhubio/aim#1519]
## 🚀 Feature

Set default ordering of Images and Audios tabs steps to `desc` in single run page.

### Motivation

Want to see the last step at first.

**Comment by ashutoshsaboo** [comment]
+1 on this. Can this be please done in the figures tab and texts tab, and for that matter all tabs too? Actually for all tabs not just these two^, it'd be a better default in my opinion to show last step first wherever the "steps"/"epoch" toggle is shown currently (since for most comparisons that's what usually matters). 

For ex: I was seeing for confusion matrices (logged using Aim.figure) currently first tab is shown which is in most cases not relevant, but I'm still logging it in case if it's required to view them later on. @VkoHov @SGevorg

**Comment by ashutoshsaboo** [comment]
I have a general request on top of this, for example in the texts and figure tab - I was seeing a toggle for steps but not epochs. Is there any reason behind that? In general epoch slider (along with the current steps slider) must be shown on all pages wherever possible - the reasoning behind this is that steps are associated to minibatches which in most cases isn't useful. But epochs denote which stage of the training it was logged in, which is far more useful to see as a user. (That being said steps slider must also be there, but epoch slider/information must be also rendered across pages). 

And once the epoch information is shown, the default should be to show last epoch in all such tabs IMHO. Can this be please done for? 

@VkoHov @SGevorg

**Comment by VkoHov** [comment]
Hey @ashutoshsaboo, thanks for this feedback. I will add it in other tabs too.

> +1 on this. Can this be please done in the figures tab and texts tab, and for that matter all tabs too? Actually for all tabs not just these two^, it'd be a better default in my opinion to show last step first wherever the "steps"/"epoch" toggle is shown currently (since for most comparisons that's what usually matters).
> 
> For ex: I was seeing for confusion matrices (logged using Aim.figure) currently first tab is shown which is in most cases not relevant, but I'm still logging it in case if it's required to view them later on. @VkoHov @SGevorg

**Comment by VkoHov** [comment]
Can you please open a separate issue for that so it would be easier to explore.

> I have a general request on top of this, for example in the texts and figure tab - I was seeing a toggle for steps but not epochs. Is there any reason behind that? Many of the explorers and other run specific tables also don't show epoch specific information to my surprise, I'm not sure why. In general epoch slider (along with the current steps slider) must be shown on all pages wherever possible ideally - the reasoning behind this is that steps are associated to mini-batches which in most cases isn't useful. But epochs denote which stage of the training it was logged in, which is far more useful to see as a user. (That being said steps slider must also be there, but epoch slider/information must be also rendered across pages).
> 
> And once the epoch information is shown, the default should be to set to show "last epoch" in all such tabs IMHO. Can this be please done for?
> 
> @VkoHov @SGevorg

**Comment by ashutoshsaboo** [comment]
I can, but reason I mentioned it here is: I'm not sure the current way of showing only steps and not epochs is even the correct solution (imho) to this feature request, and ideal solution would be to show epoch slider (along with step slider too) as well and also render it to last epoch when loading these pages, rather than just last step. Which is why I thought both were related, and if they can be tracked under the same issue, thoughts? @VkoHov @SGevorg If you still prefer for a new issue, lmk I will create one.

**Comment by SGevorg** [comment]
> I can, but reason I mentioned it here is: I'm not sure the current way of showing only steps and not epochs is even the correct solution (imho) to where this feature request is coming from, and ideal solution would be to show epoch slider (along with step slider too) as well and also render it to last epoch when loading these pages, rather than just last step. Which is why I thought both were related, and if they can be tracked under the same issue, thoughts? @VkoHov @SGevorg If you still prefer for a new issue, lmk I will create one.

@ashutoshsaboo I see your point. this issue is very specific one - to just improve the ordering. What you are raising to me sounds like a major UX decision - could be even deeper than that. 
It definitely need to be discussed under its own issue and we can explore there, we can also add connection to this so the full context is not lost.

**Comment by ashutoshsaboo** [comment]
Sure, @SGevorg thanks! Opened one here: https://github.com/aimhubio/aim/issues/1536 .

**Comment by VkoHov** [comment]
@ashutoshsaboo this feature was released with v3.8.0, please try it out and let me know if it works as expected.
