### ISSUE TITLE
Aim repo cloud-storage backups

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1690]
## 🚀 Feature

There is no out-of-box support for .aim repository backups. Users have to manually create an archive from repo directory and upload to cloud storage buckets.

### Motivation
A single-command backup of aim repos. Pre-defined clear naming/versioning across all repos. 

### Pitch
Add a CLI commands to backup and restore .aim repo in/from cloud storage. Support S3 and GCS. Backup command must create a snapshot of `.aim` directory for the given repo path. No need to fallback to the upper directories (search for `.aim`) as it's done for other CLI commands.

### Alternatives
The process of creating a snapshot and uploading it for backups can be done by simple bash script. However, providing it as out-of-box command as part of Aim CLI is better UX.

**Comment by karan2801** [comment]
I had a few questions/suggestions here:

1. There would be a few parameters that would be taken as input in the cli command such as bucket name(required), region (optional, default region would be picked up from the aws credentials and path (optional, by default it would be the current path). In case the bucket name does not exist in s3, the bucket will be created with the given bucket name and then the backup would be created. Please correct me if I am missing something
2. In order to create a unique folder in the s3 bucket, we can create a name using the current date and timestamp. Please suggest if something else needs to be done.
3. Should we create a zip file of the repo and then upload it or should we upload each file in the repo? 

@SGevorg @alberttorosyan @gorarakelyan

**Comment by gorarakelyan** [comment]
hey @karan2801, thanks for sharing the details

1. makes a lot of sense, how do you think credentials should be handled? 
2. I was thinking about passing the object name as a template like "aim-{dd}-{mm}-{yy}", thoughts?
3. For now it would be easier enabling uploading the whole repo as a single object. After we can think about extending the command and enable uploading only the runs that match the given query, for example `aim runs upload --query "run.hparams.learning_rate > 0.001`

Thoughts?

Sorry for a late response 🙏

**Comment by karan2801** [comment]
Hey @gorarakelyan 

1. I will do research on my end on how credentials can be handled and get back to you. Any ideas on this from your side? 
2. The template "aim-{dd}-{mm}-{yy}" looks good to me, what if a user uploads a backup multiple times in a single day?
3. I think there is a misunderstanding here. Is the command supposed to upload the runs from user's local project (which imports aim)? 

Thanks!

**Comment by karan2801** [comment]
I have created a [PR for review](https://github.com/aimhubio/aim/pull/1787). Kindly review the PR, and let me know your thoughts on the same.  @gorarakelyan @alberttorosyan @SGevorg

**Comment by gorarakelyan** [comment]
@karan2801 this feature has been shipped with Aim v3.11.0. Congrats on the first shipped contribution 🚀 And massive thanks for your time and effort 🙌
