### ISSUE TITLE
DVC plugin: track versions of dataset used during run

### ISSUE THREAD

**Issue by inc0** [aimhubio/aim#2423]
## 🚀 Feature

Currently [dvc_metadata](https://github.com/aimhubio/aim/blob/main/aim/sdk/objects/plugins/dvc_metadata.py) only tracks well, metadata. That is, repo location, tracked files etc. Since runs represent a training job, they would benefit from tracking version of dataset that run was created with too.

### Motivation

Models are product of both code and dataset version. While run doesn't exactly map to model, it's effectively following same pattern. If user tracks dvc dataset, it makes sense that they use, and version their data. Aim could track this DVC version that's present on run submission (or rather, when `DVCData` class is instantiated).

### Pitch

Let's track data versions!

**Comment by alberttorosyan** [comment]
Hi @inc0!
Great idea; thanks for the proposal 🙌
If you want to contribute to the code, will be happy to help 🚀

**Comment by tmynn** [comment]
Hi @inc0.
Thanks a lot for the suggestion, it's a great idea. I am working on this request 🙌
Is there a specific property in the dvc Repo that identifies the version of the dataset? Because I am wasn't able to find it in their api.
Also, as I can see from their tutorials they specify the version in git tag.

Please feel free to propose your changes in this PR
https://github.com/aimhubio/aim/pull/2447
