### ISSUE TITLE
Web page is blank after 'aim up' - possibly due to params logged

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#257]
A separate issue targeting the second part of #256 by @xwjBupt

**Comment by SGevorg** [comment]
@xwjBupt could you share more details of the params you have used? maybe specific format or other info?

**Comment by gorarakelyan** [comment]
Hi @xwjBupt,

The issue was due to `float(‘inf’)` parameter which was converted into `Infinity` object and was not recognized by JavaScript json parser. We resolved this issue, updated Aim and tested on the code you provided.

Once you upgrade Aim, please then remove `.aim` repo from working directory and rerun the training.
The issue should be gone.

**Comment by xwjBupt** [comment]
Hi, @SGevorg and @gorarakelyan , the problem has been solved!! Thanks a lot!!, but last time, i may not make myself clear that the subplot i means is like the following image:

![image](https://user-images.githubusercontent.com/35280631/98825802-e2cd3080-246f-11eb-9ecf-9510149ff78d.png)

i can use a tag ('fold all' in the image) to control some plots(train_detail_loss/*) to show or fold  so that when there are many plots, the page will be more regular to see.

besides, how do you like this idea: users can combine several graphs together? Because we may have different training settings and we want to compare the learning curves.

Thanks again for your outstanding work!!!

**Comment by SGevorg** [comment]
@xwjBupt glad it worked for you
- **re folding graphs:** I am not sure I fully get the issue. Could you describe or share what are you seeing that would require such a feature?
- **re combining several graphs in one:** Please take a look at our demo [video](https://www.youtube.com/watch?v=TeAkyRIMxx4&ab_channel=Aim), it shows the way to combine, then separate out different graphs. You just search the metrics divided by comma and the plots will be rendered.

If you could describe your use cases in more detail, we could be more helpful. Otherwise we probably haven't fully got the issues yet?

**Comment by SGevorg** [comment]
@xwjBupt could you open a separate issue for this?
https://github.com/aimhubio/aim/issues/257#issuecomment-725468962

**Comment by xwjBupt** [comment]
OK. I am closing this,thanks!! @SGevorg
