### ISSUE TITLE
can I add some comments manually for some experiments on webpage?

### ISSUE THREAD

**Issue by qinzhi-0110** [aimhubio/aim#291]
Thank you for your awesome work! I want to manually add some notes for some experiments on the webpage. How should I do this?

**Comment by SGevorg** [comment]
@qingzhiwu we don't have it yet in the product. But it's in the backlog as it's been much requested feature. 
If the priorities don't change we should be able to ship that feature in the next few weeks.

Meanwhile would love to invite you to join [Aim slack community](https://join.slack.com/t/aimstack/shared_invite/zt-jhlp5og5-jw5TnkWBfjVrrGXLsdMOBw) to stay up to date with the changes.

**Comment by qingzhiwu** [comment]
Thank you for reply @SGevorg 
We look forward to your work very much！

**Comment by ashutoshsaboo** [comment]
Ping on this as it's been open since 2020 for adding capability to add/edit/delete multi-line notes from Aim UI itself rather than SDK. This is quite an essential feature. The use-case is that while comparing runs, to quickly jot down notes on Aim UI itself (so all run specific details stay on the same page) rather than using some notes application to jot them down. This should massively increase user experience. @roubkar : Please add other details from our slack conversation for this. 

While taking notes: please see if there's a capability to add a wysiwyg markdown editor to enable ease for the user. 

cc/: @SGevorg @gorarakelyan @roubkar

**Comment by ashutoshsaboo** [comment]
Some ideas: In addition, please see if on all the pages a small floating popover can be added to the bottom right of the page or somewhere - to add notes from any page. The popover can have capability to add note, to associate the new note to a specific run name/hash or multiple runs/experiments. 

The advantage of this is that, say if i'm on the texts/image explorer/any other page and doing some analysis, and have some observations to quickly jot down - then having a way to quickly add it from the same page would be quite good to have. For folks, who don't prefer to have the popover there can be an option somewhere to close it for the session across all pages - then they can manually go to the notes tab to add notes if they want to. 

@SGevorg @roubkar @arsengit @gorarakelyan

**Comment by arsengit** [comment]
Hi there. A Brief glimpse at how the `Notes` tab can be implemented in Aim UI. This layout gives the ability to see live changes of the `markdown`, also `resize` the panel between preview and `markdown` panels. Most likely the `markdown` panel will be on the left side. 
As for adding notes from any page, that feature should be **explored**. For the next iterations maybe will be the ability to save _**multiple**_ markdowns for the run.

![Single Run Explorer_notes V2](https://user-images.githubusercontent.com/44676488/158881109-990a3fb0-e683-4398-b03d-c4322397ec43.png)

**Comment by arsengit** [comment]
Hi there. A brief glimpse at how the `Notes` tab can be implemented in Aim UI. This layout gives the ability to see live changes of the `markdown`, also `resize` the panel between preview and `markdown` panels. Most likely the `markdown` panel will be on the left side.
As for adding notes from any page, that feature should be explored. For the next iterations maybe will be the ability to save multiple markdowns for the run.

![Single Run Explorer_notes V2](https://user-images.githubusercontent.com/44676488/158890005-3dd0f665-d537-46b1-9b29-1fd96c53757b.png)

**Comment by ashutoshsaboo** [comment]
Is it possible to use a wysiwyg editor (which accepts for both manual markdown as well as wysiwyg input both) rather? It'll much lesser space and is much more user friendly without any doubt. Advantage of lesser space is that when you add capability to log notes from any page then, having a smaller popover editor might be more beneficial. In terms of my preference, I'd prefer for the feature of adding notes from any page as more important (relatively I mean) than multiple notes. 

If you're looking for an editor, potential options: https://ui.toast.com/tui-editor, https://milkdown.dev . Both are open source and i think well maintained too (you can compare once too). @arsengit

**Comment by arsengit** [comment]
Hey @ashutoshsaboo , we’re currently exploring the implementation on the technical side, thanks a lot for the references of `wysiwyg` editors it helps a lot.
Will share an initial version of the implementation once the technology/lib will be selected.

**Comment by ashutoshsaboo** [comment]
Thanks, re editor: please ensure it's wysiwyg + accepts actual markdown both, but without a preview pane like you showed above (for users who are comfortable with it, writing actual markdown is much quicker than tapping on the editor buttons again and again). 

Re popover that I mentioned above: You can look at how certain websites have a form popover modal for their chat supports for example, see how Binance does it for example (look for the chat support popover in bottom right of screen): https://www.binance.com/en/support . Aim could similarly have a popover form at each page, asking for note text that needs to be entered and a list of run name/experiment names that the note needs to be associated to - 1 note can be persisted to multiple runs (or if not persisted have 1:many mapping and persisted only once whatever your architecture allows for) at the same time from this popover. There can be a simple 'x' symbol or somewhere in the setting to disable the popover for those who don't want it (similar to the disable Live update toggle on the Runs page).

Use-case: If I'm on text explorer page (or one of the other explorer pages) for example, and want to quickly log few observations by looking at the model results, I'd quickly go to the popover add my observations add the run name(s) it should be assigned to - for example: i might have a comparison kind of an observation such as: "runA is making xyz kind of mistakes vs runB while runB makes abc kind of mistakes during prediction", in which case that note I'd want to assign to both runA and runB. 

From the notes page which would be under the run single page, there there's no need to ask for which run the note it should be assigned to - since there it's implicit as the run page is already selected and the note would only correspond to a single run here (which is the selected run page from where user is adding notes). 

My take on just associating notes to the run single page is that it's very fragmented which is not the ideal way a user would want to work (atleast imho). Think of it like this: Tensorboard/Mlflow only render your logged data in a single fragmented table of sorts. Aim is much more powerful, because it allows for complex sorting/filtering/grouping over the logged data. Similarly, having notes on a single page is a very fragmented UX in my opinion (in analogy: this is similar to the tensorboard/mlflow for how they render their tables just in a static manner). Having ability to add notes from anywhere makes it much more free-flowing for the user, and a more realistic way of how a powerful experiment tracker must look like. Especially given that Aim's explorers are already so much more powerful - you give the user ability to see data across runs today, but to log observations there must be some capability too (which is where the notes popover from any page should help that I described above). Hope this helps. @arsengit

**Comment by arsengit** [comment]
Thanks for the helpful mentions and references @ashutoshsaboo. The ability to save notes from any page will be explored by our team. I will share the decision and the details. As for the WYSIWYG editor, we decided to use Toast UI.

**Comment by arsengit** [comment]
Hey  @qinzhi-0110 , this feature has been shipped with v3.9.0.
To upgrade please run pip install aim --upgrade

**Comment by ashutoshsaboo** [comment]
Hey @arsengit was the ability to add notes from any page also shipped? You had mentioned earlier above that it was still being explored after I had shared some ideas and suggestions above.

**Comment by gorarakelyan** [comment]
@ashutoshsaboo sorry for a late reply. There is an idea of creating a modal/overlay for displaying run overview/summary from any page. I guess this might be a good place to enable creating notes as well.

See recently added feature in GitHub projects as a reference:
![image](https://user-images.githubusercontent.com/13848158/171668065-9a1ad091-916d-4cf1-aa1b-9df530eb164c.png)

What do you think?

**Comment by ashutoshsaboo** [comment]
Sounds very cool, are you saying in the popover the only functionality that'd be there is of the notes? Or would it be a tab like environment similar to the single run specific page (having all the tabs like metrics, text, overview page, notes etc)? @gorarakelyan

**Comment by gorarakelyan** [comment]
@ashutoshsaboo currently we are more inclined to the second option - abridged version which provides overview of the run + some quick actions e.g. edit run name, description attach/detach tags or notes, archive/unarchive run. But it is still in an exploration phase and any feedback is welcome.
