### ISSUE TITLE
Artifact name validation is too strict

### ISSUE THREAD

**Issue by radao** [aimhubio/aim#321]
I see artifact names are validated to only include alphanumeric characters by the follow regex: `re.search(r'^[^\d\W]\w*\Z', str(name))`

This does not allow for artifact names such as `total_loss` or `fast_rcnn/cls_accuracy`. Is there any particular reason why artifact names cannot contain special characters?

**Comment by radao** [comment]
Silly me, I see in the docs now the preferred divider is an underscore. Still wondering why not allow other dividers in metric names though?

**Comment by gorarakelyan** [comment]
Hi @radao, 

Restrictions are applied in order to keep select/search AimQL queries lucid and avoid potential forward-compatibility issues with the next versions. Think of artifact names like table columns of SQL databases.

You can use [context arguments](https://github.com/aimhubio/aim#track) to pass an additional context to the metrics you are tracking, please check out more detailed answer [here](https://github.com/aimhubio/aim/issues/256#issuecomment-723833344).

**Comment by radao** [comment]
Makes sense! And thanks for the prompt reply, much appreciated. More info in the docs about this behavior would be a helpful addition.
