### ISSUE TITLE
Remove docker to reduce the barriers for entry

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#333]
Currently AimUI is packaged as a docker container.

Initially it has been thought of as a positive cross-platform solution, however it has been shown that docker is not famous among ML researchers and it's a major barrier:
- University systems usually don't grant a kind of permission to use docker, so most of the time a special request needs to be made to IT
- There are user-groups entanglement, root permission issues that have happened among users
- Ability to integrate with Colab and similar environments

**Comment by ThorJonsson** [comment]
Hi, I am a big fan of this system you have made. However I cannot use it on any of the supercomputing clusters I have access to because docker is not allowed on these clusters since it poses major security concerns. 

What can I do until this issue is resolved? At the moment I can only use aim on AWS systems or something similar but I am in the process of moving away from using such systems altogether since they are really expensive...

**Comment by SGevorg** [comment]
Hi @ThorJonsson this feature is work in progress right now.
Check out this PR: https://github.com/aimhubio/aimui/pull/259
Hopefully within the next week it's fully done. 
Thanks for kind words 🙌.
Once we have an early candidate will publish over here and in the community to try out.

**Comment by ThorJonsson** [comment]
Hey! How's the progress on this? Would love to get to review some new results from our experiments with Aim this week and spread the good word of the work you guys are doing.

**Comment by gorarakelyan** [comment]
Hi @ThorJonsson, 

Awesome! We have already submitted a release candidate of dockerless version of Aim. You can try it out by installing the latest RC `pip install aim==2.5.0rc5` and running as usual `aim up`. We are currently testing it in different environments to resolve issues before the stable release. In case of any bugs, feel free to report them.
