### ISSUE TITLE
Improve line chart zooming experience

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#414]
**Problem**
The zoom mode is enabled by clicking on the zoom icon on the right sidebar and is auto disabled after the first zooming. It is inconvenient when zooming for multiple times is needed.

**Solution**
Provide a new zooming mode: keep zooming while it's not deactivated manually.

**Comment by roubkar** [comment]
@gorarakelyan please can you provide feedback regarding text copies?

![Screen Shot 2021-04-12 at 13 55 10](https://user-images.githubusercontent.com/9951653/114376483-b6d8e700-9b96-11eb-9f90-db2eaff67a9a.png)

**Comment by gorarakelyan** [comment]
@SGevorg do you have any suggestions for the zooming modes descriptions?

**Comment by roubkar** [comment]
Also added `zoom out` text to indicate that zooming is applied on chart, thoughts?

![Screen Shot 2021-04-12 at 16 28 43](https://user-images.githubusercontent.com/9951653/114394365-29a08d00-9bac-11eb-93e6-3685aaec5e15.png)

**Comment by gorarakelyan** [comment]
What about displaying only zoom-out icon? I guess there is no too much space, especially when lines are grouped and multiple charts are displayed in the explore screen.

**Comment by SGevorg** [comment]
> @SGevorg do you have any suggestions for the zooming modes descriptions?

I was thinking of having the zoom button highlighted when a chart is zoomed - could be minimal but a good start. Thoughts? 
The immediate issue is that it's not obvious on the UI when the zoom is enabled.

**Comment by roubkar** [comment]
@SGevorg currently zoom in button is highlighted when you want to apply zooming, you can detect whether zooming is already applied by the state of zoom out button if no zooming is applied it will be disabled. However, I agree that it's not the ideal solution so I'm thinking of also adding a zoom-out button to the chart title so it will always be visible and you also will be able to zoom out right from the chart without navigating to the controls sidebar.

As for the text copies in the new popover, I'd like to introduce a new mode for zooming to improve the experience in the case of multiple zooms so that you don't have to always enable zooming after each step.

Would like to know your thoughts on whether the texts are good or we should improve them?

![Screen Shot 2021-04-12 at 18 30 34](https://user-images.githubusercontent.com/9951653/114411388-2f529e80-9bbd-11eb-9609-dbd8c73b8481.png)

**Comment by gorarakelyan** [comment]
Great job!
