### ISSUE TITLE
Activity API error

### ISSUE THREAD

**Issue by vopani** [aimhubio/aim#418]
I have an experiment but the UI shows 0.

<img width="1142" alt="Screenshot 2021-03-30 at 5 51 54 PM" src="https://user-images.githubusercontent.com/8954217/112987983-efcd9080-9180-11eb-9352-ce0635cb164e.png">

Seems to be some problem with the activity API call.
[error.txt](https://github.com/aimhubio/aim/files/6228983/error.txt)

Funnily, the issue is on Chrome. It works correctly on Firefox.

**Comment by gorarakelyan** [comment]
Hm, that's super weird, what version of Chrome do you use?

**Comment by vopani** [comment]
Version 89.0.4389.90 (Official Build) (x86_64)
Mac OS Version 11.2.2

**Comment by gorarakelyan** [comment]
Thanks a lot. 
Also can you please share what timezone is set on chrome? You can get it by running `Intl.DateTimeFormat().resolvedOptions().timeZone` command in chrome console.

**Comment by gorarakelyan** [comment]
Hi @vopani,

The problem was due to not receiving timezone cookie from the browser. 

Couldn't reproduce the issue and set a default timezone — `GMT`, hence the activity block will be displayed, but some datetime mismatch can happen. 
Please try it out and check if it works - `aim upgrade && aim up`.

re timezone cookie: Do you have any thoughts why it could happen? Maybe there were browser restrictions forbidding sending it?

Thanks.

**Comment by vopani** [comment]
It works after the upgrade. Thanks a lot!
I tested it on multiple browsers, with / without incognito, with / without caching / cookies, and it all works.

Sorry, I don't know much on how cookies / browsers work. I will probably check in detail or raise this in case I face it again.

**Comment by gorarakelyan** [comment]
Awesome, thanks for sharing the details!
